# Generated by Django 6.0.3 on 2026-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBreedingPairs',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('female_pet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('male_pet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pairing_date', models.DateField(blank=True, null=True)),
                ('expected_due_date', models.DateField(blank=True, null=True)),
                ('litter_size_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('female_id', models.IntegerField(blank=True, null=True)),
                ('male_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'active_breeding_pairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_id', models.IntegerField(blank=True, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('residency_type', models.CharField(blank=True, max_length=50, null=True)),
                ('has_other_pets', models.CharField(blank=True, max_length=10, null=True)),
                ('pet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adoption_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InviteKeys',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_key', models.CharField(max_length=50, unique=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invite_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LitterHistory',
            fields=[
                ('litter_id', models.AutoField(primary_key=True, serialize=False)),
                ('female_pet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('litter_date', models.DateField(blank=True, null=True)),
                ('puppy_kitten_count', models.IntegerField(blank=True, null=True)),
                ('adoption_status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'litter_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetsAccounts',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('health_status', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_traits', models.TextField(blank=True, null=True)),
                ('reason_for_adoption', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_username', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pets_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('session_token', models.CharField(blank=True, max_length=100, null=True)),
                ('trusted_devices', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetAppointments',
            fields=[
                ('appt_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('appt_time', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vet_appointments',
                'managed': False,
            },
        ),
    ]
