# Generated by Django 6.0.3 on 2026-04-08 02:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_treat_refill',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='super_treats',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ActiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Owner Approval'), ('approved', 'Approved & Messaging')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet1', to='pets.petsaccounts')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet2', to='pets.petsaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='PetMatchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=15)),
                ('require_vet_verified', models.BooleanField(default=False)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_preferences', to='pets.petsaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('super_like', 'Super Treat')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to='pets.petsaccounts')),
                ('sender_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to='pets.petsaccounts')),
            ],
            options={
                'unique_together': {('sender_pet', 'receiver_pet')},
            },
        ),
    ]
